
def stop_media(timestamp: int): # TODO: Do we need any other parameter?
    pass # TODO: ...

def resume_media(timestamp: int): # TODO: Do we need any other parameter?
    pass # TODO: ...

def jump_to_timestamp(from_timestamp: int, to_timestamp: int): # TODO: Do we need any other parameter?
    pass # TODO: ...
